"""
Official Master List of 80 Branches of The Nasik Merchants Co-operative Bank Ltd. (Namco Bank)
"""

NAMCO_80_BRANCHES = [
    {"branch_code": "NSK-001", "branch_name": "CBS Head Office, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-002", "branch_name": "Canada Corner Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-003", "branch_name": "Mumbai Naka Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-004", "branch_name": "Panchavati Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-005", "branch_name": "College Road Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-006", "branch_name": "Nashik Road Branch", "city": "Nashik"},
    {"branch_code": "NSK-007", "branch_name": "Satpur Industrial Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-008", "branch_name": "Ambad Industrial Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-009", "branch_name": "CIDCO Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-010", "branch_name": "Gangapur Road Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-011", "branch_name": "Deolali Camp Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-012", "branch_name": "Indira Nagar Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-013", "branch_name": "Govind Nagar Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-014", "branch_name": "Pathardi Phata Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-015", "branch_name": "Pawan Nagar Branch, CIDCO, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-016", "branch_name": "Upnagar Branch, Nashik Road", "city": "Nashik"},
    {"branch_code": "NSK-017", "branch_name": "Jail Road Branch, Nashik Road", "city": "Nashik"},
    {"branch_code": "NSK-018", "branch_name": "Old City Main Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-019", "branch_name": "Raviwar Peth Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-020", "branch_name": "Bhadrakali Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-021", "branch_name": "Dwarka Circle Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-022", "branch_name": "Dindori Road Branch, Panchavati", "city": "Nashik"},
    {"branch_code": "NSK-023", "branch_name": "Makhmlabad Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-024", "branch_name": "Adgaon Naka Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-025", "branch_name": "Parijat Nagar Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-026", "branch_name": "Untwadi Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-027", "branch_name": "Ashok Stambh Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-028", "branch_name": "MG Road Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-029", "branch_name": "Sharanpur Road Branch, Nashik", "city": "Nashik"},
    {"branch_code": "NSK-030", "branch_name": "Tidke Colony Branch, Nashik", "city": "Nashik"},
    
    # Nashik District Rural & Suburbs (31 to 50)
    {"branch_code": "NSK-031", "branch_name": "Sinnar Main Branch", "city": "Sinnar"},
    {"branch_code": "NSK-032", "branch_name": "Sinnar MIDC Branch", "city": "Sinnar"},
    {"branch_code": "NSK-033", "branch_name": "Ozar Town Branch", "city": "Ozar"},
    {"branch_code": "NSK-034", "branch_name": "Ozar HAL Mig Township Branch", "city": "Ozar"},
    {"branch_code": "NSK-035", "branch_name": "Pimpalgaon Baswant Branch", "city": "Pimpalgaon"},
    {"branch_code": "NSK-036", "branch_name": "Lasalgaon APMC Branch", "city": "Lasalgaon"},
    {"branch_code": "NSK-037", "branch_name": "Niphad Town Branch", "city": "Niphad"},
    {"branch_code": "NSK-038", "branch_name": "Yeola Paithani City Branch", "city": "Yeola"},
    {"branch_code": "NSK-039", "branch_name": "Malegaon Camp Branch", "city": "Malegaon"},
    {"branch_code": "NSK-040", "branch_name": "Malegaon City Branch", "city": "Malegaon"},
    {"branch_code": "NSK-041", "branch_name": "Manmad Junction Branch", "city": "Manmad"},
    {"branch_code": "NSK-042", "branch_name": "Satana Main Branch", "city": "Satana"},
    {"branch_code": "NSK-043", "branch_name": "Kalwan Branch", "city": "Kalwan"},
    {"branch_code": "NSK-044", "branch_name": "Deola Branch", "city": "Deola"},
    {"branch_code": "NSK-045", "branch_name": "Chandwad Branch", "city": "Chandwad"},
    {"branch_code": "NSK-046", "branch_name": "Dindori Town Branch", "city": "Dindori"},
    {"branch_code": "NSK-047", "branch_name": "Trimbakeshwar Temple Branch", "city": "Trimbakeshwar"},
    {"branch_code": "NSK-048", "branch_name": "Igatpuri Hill City Branch", "city": "Igatpuri"},
    {"branch_code": "NSK-049", "branch_name": "Ghoti Market Branch", "city": "Ghoti"},
    {"branch_code": "NSK-050", "branch_name": "Surgana Tribal Area Branch", "city": "Surgana"},
    
    # Pune & Western Maharashtra (51 to 62)
    {"branch_code": "PUN-051", "branch_name": "Pune FC Road Branch, Shivajinagar", "city": "Pune"},
    {"branch_code": "PUN-052", "branch_name": "Pune Kothrud Branch", "city": "Pune"},
    {"branch_code": "PUN-053", "branch_name": "Pune Camp Branch, MG Road", "city": "Pune"},
    {"branch_code": "PUN-054", "branch_name": "Pune Hadapsar Branch", "city": "Pune"},
    {"branch_code": "PUN-055", "branch_name": "Pune Baner Branch", "city": "Pune"},
    {"branch_code": "PUN-056", "branch_name": "Pune Wakad Branch", "city": "Pune"},
    {"branch_code": "PUN-057", "branch_name": "Pune Pimpri-Chinchwad Branch", "city": "PCMC"},
    {"branch_code": "PUN-058", "branch_name": "Pune Bhosari MIDC Branch", "city": "PCMC"},
    {"branch_code": "PUN-059", "branch_name": "Ahmednagar Main Branch", "city": "Ahmednagar"},
    {"branch_code": "PUN-060", "branch_name": "Ahmednagar MIDC Branch", "city": "Ahmednagar"},
    {"branch_code": "PUN-061", "branch_name": "Sangamner Branch", "city": "Sangamner"},
    {"branch_code": "PUN-062", "branch_name": "Shirdi Sai Nagar Branch", "city": "Shirdi"},

    # Mumbai & MMR Network (63 to 72)
    {"branch_code": "MUM-063", "branch_name": "Mumbai Fort Corporate Branch", "city": "Mumbai"},
    {"branch_code": "MUM-064", "branch_name": "Mumbai Dadar West Branch", "city": "Mumbai"},
    {"branch_code": "MUM-065", "branch_name": "Mumbai Andheri East Branch", "city": "Mumbai"},
    {"branch_code": "MUM-066", "branch_name": "Mumbai Borivali West Branch", "city": "Mumbai"},
    {"branch_code": "MUM-067", "branch_name": "Mumbai Ghatkopar Branch", "city": "Mumbai"},
    {"branch_code": "MUM-068", "branch_name": "Thane Naupada Branch", "city": "Thane"},
    {"branch_code": "MUM-069", "branch_name": "Thane Ghodbunder Road Branch", "city": "Thane"},
    {"branch_code": "MUM-070", "branch_name": "Navi Mumbai Vashi Branch", "city": "Navi Mumbai"},
    {"branch_code": "MUM-071", "branch_name": "Kalyan West Branch", "city": "Kalyan"},
    {"branch_code": "MUM-072", "branch_name": "Panvel Market Branch", "city": "Panvel"},

    # North Maharashtra & Khandesh (73 to 80)
    {"branch_code": "KHD-073", "branch_name": "Jalgaon City Branch", "city": "Jalgaon"},
    {"branch_code": "KHD-074", "branch_name": "Jalgaon MIDC Branch", "city": "Jalgaon"},
    {"branch_code": "KHD-075", "branch_name": "Bhusawal Railway Town Branch", "city": "Bhusawal"},
    {"branch_code": "KHD-076", "branch_name": "Dhule Main Agra Road Branch", "city": "Dhule"},
    {"branch_code": "KHD-077", "branch_name": "Nandurbar Town Branch", "city": "Nandurbar"},
    {"branch_code": "KHD-078", "branch_name": "Chhatrapati Sambhajinagar (Aurangabad) Town Branch", "city": "Aurangabad"},
    {"branch_code": "KHD-079", "branch_name": "Chhatrapati Sambhajinagar CIDCO Branch", "city": "Aurangabad"},
    {"branch_code": "KHD-080", "branch_name": "Solapur Textile City Branch", "city": "Solapur"}
]
