# Generated by Django 5.1.15 on 2026-09-16 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AddField(
            model_name='bankofficer',
            name='activation_status',
            field=models.CharField(default='ACTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='bankofficer',
            name='last_2fa_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankofficer',
            name='two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='tbl_admin_audit_logs',
        ),
        migrations.CreateModel(
            name='OfficerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=120, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='consent_portal.bankofficer')),
            ],
            options={
                'verbose_name': 'Officer Session',
                'verbose_name_plural': 'Officer Sessions',
                'db_table': 'tbl_officer_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_token', models.CharField(db_index=True, max_length=80, unique=True)),
                ('otp_hash', models.CharField(max_length=255)),
                ('delivery_channel', models.CharField(default='SMS', max_length=20)),
                ('delivery_target', models.CharField(blank=True, max_length=100, null=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('resend_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_invalidated', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_challenges', to='consent_portal.bankofficer')),
            ],
            options={
                'verbose_name': '2FA Challenge',
                'verbose_name_plural': '2FA Challenges',
                'db_table': 'tbl_two_factor_challenges',
                'ordering': ['-created_at'],
            },
        ),
    ]
